name: 🚀 Auto Deploy Surge

on:
  push:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4

    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: 'npm'

    - name: 📦 Install deps (npm)
      run: npm install

    - name: 🔨 Build projet (npm)
      run: npm run build

    - name: 🧩 SPA routing fix (200.html)
      run: |
        cd dist              # <-- change en 'build' si besoin
        cp index.html 200.html
      # Sous Windows runner ça serait 'copy', mais sur ubuntu 'cp' marche.

    - name: 📤 Deploy Surge
      uses: dswistowski/surge-sh-action@v1
      with:
        login: ${{ secrets.SURGE_LOGIN }}
        token: ${{ secrets.SURGE_TOKEN }}
        project: dist              # ou build, selon ton output
        domain: xeval.surge.sh
