name: 🚀 Auto Deploy Surge

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4

    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: 'npm'

    - name: 📦 Install deps
      run: npm install

    - name: 🔨 Build projet
      run: npm run build

    - name: 🧩 SPA routing fix (200.html)
      run: |
        # Vérifiez que le dossier est bien 'dist'
        cp dist/index.html dist/200.html

    - name: 📤 Deploy to Surge
      run: npx surge --project ./dist --domain xeval.surge.sh
      env:
        SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
